# Generated by Django 5.0.2 on 2024-04-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_instock_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="General", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(default="New", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
