# Generated by Django 5.0.2 on 2024-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_brand_category_contact_product_disconte_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Brand",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="product",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="product",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(default="General", max_length=255),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
