# Generated by Django 5.0.2 on 2024-04-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_delete_brand_delete_category_remove_comment_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
    ]
