# Generated by Django 5.0.2 on 2024-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_cart_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="disconte",
            new_name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="favoted",
        ),
        migrations.RemoveField(
            model_name="product",
            name="label",
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.png", upload_to="products/"),
        ),
    ]
