# Generated by Django 5.0.2 on 2024-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default="General", max_length=255),
        ),
    ]
