# Generated by Django 5.0.3 on 2024-04-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_rating_product_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Rating',
        ),
    ]
