# Generated by Django 5.0.3 on 2024-04-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
