# Generated by Django 5.0.2 on 2024-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(default="", max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="instock",
            field=models.ImageField(default=1, upload_to=""),
        ),
    ]
